const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // This will include all directories except those excluded
      exclude: ['.hidden/**'], // Exclude the entire Hidden directory
    },
  ],
};

export default sidebars;